default:
  service:
    name: sr-library
    port: 3000
    databases:
      main:
        dialect: postgresql
        host: 127.0.0.1
        port: 5433
        dbName: entel-postgresql
        user: postgres
        password: developer123
    jwt:
  metadata:
    enviroment: local
    cookie:
      domain: ''
      sameSite: 'None'
      httpOnly: false
